extends: default

rules:
  line-length: disable
  document-start: disable
  comments: disable
  comments-indentation: disable
  truthy:
    check-keys: false
  indentation:
    spaces: consistent
    indent-sequences: whatever
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
